version: '3'

services:
  reverse-proxy-dev:
    image: nginx:1.20.1
    ports:
      - 80:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    container_name: reverse-proxy-dev
    logging:
      driver: none
  
  frontend-dev:
    image: recom-frontend-dev
    build:
      context: ./recom-frontend # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
     - ./recom-frontend:/recom-frontend # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
     - 3000:3000
    environment: 
      - CHOKIDAR_USEPOLLING=true
    container_name: recom-frontend-dev # This will name the container recom-frontend

  backend-dev:
    image: recom-backend-dev
    build:
      context: ./recom-backend
      dockerfile: dev.Dockerfile
    volumes:
     - ./recom-backend:/recom-backend
    ports:
     - 4000:4000
    environment: 
      - CHOKIDAR_USEPOLLING=true
      - BACKEND_PORT=${BACKEND_PORT}
      - DB_URI=${DB_URI_DEV}
      - JWT_SECRET=${JWT_SECRET}
    container_name: recom-backend-dev

  mongo-dev:
    image: mongo
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=root
     - MONGO_INITDB_ROOT_PASSWORD=example
     - MONGO_INITDB_DATABASE=store
    volumes:
     - ./recom-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
     - ./recom-backend/mongo_data:/data/db
    logging:
      driver: none
    container_name: "mongo-container"

  