version: '3.8'

services:
  recom-traefik-proxy:
    image: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: recom-traefik-proxy

  recom-admin:
    image: recom-admin
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - 3050:3050
    labels:
      - traefik.enable=true
      - traefik.http.routers.admin.rule=Host(`admin.localhost`)
      - traefik.http.routers.admin.entrypoints=web
    container_name: recom-admin

  recom-client:
    image: recom-client
    build:
      context: ./client # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read
    ports:
     - 3000:3000
    labels:
      - traefik.enable=true
      - traefik.http.routers.client.rule=Host(`localhost`)
      - traefik.http.routers.client.entrypoints=web
    container_name: recom-client # This will name the container recom-frontend

  recom-server:
    image: recom-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
     - 4000:4000
    environment: 
      - DB_URI=${DB_URI}
      - JWT_SECRET=${JWT_SECRET}
    labels:
      - traefik.enable=true
      - traefik.http.routers.server.rule=Host(`api.localhost`)
      - traefik.http.routers.server.entrypoints=web
    container_name: recom-server