version: '3.8'

services:
  reverse-proxy:
    image: traefik:v2.6
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: reverse-proxy
    logging:
      driver: none

  frontend:
    image: recom-frontend
    build:
      context: ./recom-frontend # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read
    ports:
     - 3000:3000
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`localhost`)
      - traefik.http.routers.frontend.entrypoints=web
    container_name: recom-frontend # This will name the container recom-frontend

  backend:
    image: recom-backend
    build:
      context: ./recom-backend
      dockerfile: Dockerfile
    ports:
     - 4000:4000
    environment: 
      - BACKEND_PORT=${BACKEND_PORT}
      - DB_URI=${DB_URI_PROD}
      - JWT_SECRET=${JWT_SECRET}
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=Host(`api.localhost`)
      - traefik.http.routers.backend.entrypoints=web
    container_name: recom-backend