version: '3.8'

services:
  prod-nginx-proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    container_name: prod-nginx-proxy

  prod-recom-frontend:
    image: recom-frontend
    build:
      context: ./recom-frontend # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read
    ports:
     - 3000:3000
    container_name: prod-recom-frontend # This will name the container recom-frontend

  prod-recom-backend:
    image: recom-backend
    build:
      context: ./recom-backend
      dockerfile: Dockerfile
    ports:
     - 4000:4000
    environment: 
      - DB_URI=${DB_URI_PROD}
      - JWT_SECRET=${JWT_SECRET}
    container_name: prod-recom-backend