version: '3.8'

# development Docker services
services:
  # local mongo database with initial values
  # defined in mongo/mongo-init.js
  mongo:
    image: mongo:5.0.6@sha256:b0abf19259902648be5ac17479dd4c65e037c3292c9eb09181f087687bca5102
    command:
      - --logpath
      - /var/log/mongodb/mongod.log
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=root
     - MONGO_INITDB_ROOT_PASSWORD=example
     - MONGO_INITDB_DATABASE=store
    volumes:
     - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
     - ./mongo/mongo_data:/data/db
    container_name: mongo