version: '3.8'

services:
  recom-nginx-proxy:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    container_name: recom-nginx-proxy

  recom-frontend:
    image: recom-frontend
    build:
      context: ./frontend # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read
    ports:
     - 3000:3000
    container_name: recom-frontend # This will name the container recom-frontend

  recom-backend:
    image: recom-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
     - 4000:4000
    environment: 
      - DB_URI=${DB_URI}
      - JWT_SECRET=${JWT_SECRET}
    container_name: recom-backend