name: CI&CD

env:
  SERVICE: recom
  REGION: europe-north1

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v3
      - uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS_JSON }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env.production
      - name: Build and Push Container
        run: |-
          DOCKER_BUILDKIT=1 docker build -t gcr.io/${{ secrets.GCP_CREDENTIALS_PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }} .
          docker push gcr.io/${{ secrets.GCP_CREDENTIALS_PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm & dotenv-cli
        run: npm install -g pnpm dotenv-cli

      - name: Deploy container to Cloud Run
        id: deploy
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          service: ${{ env.SERVICE }}
          image:
            gcr.io/${{ secrets.GCP_CREDENTIALS_PROJECT_ID }}/${{ env.SERVICE
            }}:${{ github.sha }}
          region: ${{ env.REGION }}
          env_vars_file: .env.production

      - name: "Service output"
        run: 'curl "${{ steps.deploy.outputs.url }}"'
